webapp/sptool/api/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from . import views

from .views import GenderViewSet
from .views import AgeViewSet
from .views import EducationViewSet
from .views import OccupationViewSet
from .views import CountryViewSet
from .views import VideoViewSet
from .views import UserViewSet
from .views import ActionViewSet
from .views import TermViewSet
from .views import EnrichmentViewSet

router = routers.DefaultRouter()
router.register(r'user', UserViewSet)
router.register(r'video', VideoViewSet)
router.register(r'gender', GenderViewSet)
router.register(r'age', AgeViewSet)
router.register(r'education', EducationViewSet)
router.register(r'occupation', OccupationViewSet)
router.register(r'country', CountryViewSet)
router.register(r'action', ActionViewSet)
router.register(r'term', TermViewSet)
router.register(r'enrichment', EnrichmentViewSet)

urlpatterns = [

    url(r'^', include(router.urls)),

    url(r'^demographics/', views.demographics),

    url(r'^user/(?P<username>[0-9 a-z.A-Z_]+)/watch$', views.user_watch),
    url(r'^user/(?P<username>[0-9 a-z.A-Z_]+)/actions$', views.user_actions),

    url(r'^user/(?P<username>[0-9 a-z.A-Z_]+)/recommend_videos$', views.recommend_videos),

    url(r'^user/(?P<username>[0-9 a-z.A-Z_]+)/update_profile$', views.update_profile),

    url(r'^user/(?P<username>[0-9 a-z.A-Z_]+)/friends$', views.show_friends),
    url(r'^user/(?P<username>[0-9 a-z.A-Z_]+)/add_friend$', views.add_friend),
    url(r'^user/(?P<username>[0-9 a-z.A-Z_]+)/remove_friend$', views.remove_friend),
    url(r'^user/(?P<username>[0-9 a-z.A-Z_]+)/recommend_friends$', views.recommend_friends),

    url(r'^search_videos$', views.search_videos),

    url(r'^target$', views.target),
    url(r'^videos_to_target$', views.recommend_videos_to_target),

    url(r'^user/(?P<username>[0-9 a-z.A-Z_]+)/recommend_enrichments$', views.recommend_enrichments),
    url(r'^user/(?P<username>[0-9 a-z.A-Z_]+)/enrichments_from_set$', views.recommend_enrichment_from_set),
    url(r'^enrichments_to_target$', views.recommend_enrichments_to_target),
    url(r'^enrichments_to_target_for_IEVCT', views.recommend_enrichments_to_target_for_IEVCT),

    url(r'^import_video$', views.import_video),
    url(r'^delete_videos$', views.delete_videos),

    url(r'^import_enrichments$', views.import_enrichments),
    url(r'^delete_enrichments$', views.delete_enrichments),
    url(r'^delete_enrichments_on_videos$', views.delete_enrichments_on_videos),
    url(r'^delete_enrichments_on_project$', views.delete_enrichments_on_project)
]

webapp/sptool/gui/urls.py
from django.conf.urls import url, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [

    url(r'^$', views.home, name="home"),
    url(r'^terms/$', views.terms, name="terms"),
    url(r'^about/$', views.about, name="about"),

    url(r'^signup/$', views.signup, name="signup"),
    url(r'^profile/$', views.profile, name="profile"),
    url(r'^login/$', auth_views.login, {'template_name': 'gui/login.html'}, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^delete_user/$', views.delete, name="delete"),

    url(r'^videos/$', views.videos, name="videos"),
    url(r'^videos/(?P<euscreen>[-0-9 a-zA-Z_]+)/$', views.play_video, name="play_video"),

    url(r'^business/$', views.business, name="business"),

    url(r'^export/$', views.export, name="export"),

    url(r'^', include('django.contrib.auth.urls', namespace='auth')),
    url(r'^', include('social_django.urls', namespace='social')),

    url(r'^dashboard/$', views.dashboard, name="dashboard")
]

webapp/sptool/sptool_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^api/', include('api.urls')),

    url(r'^admin/', admin.site.urls),

    url(r'^', include('gui.urls')),
]

webapp/sptool/api/models/terms.py
from django.db import models


class Term(models.Model):
    term = models.CharField(max_length=50)
    long_name = models.CharField(max_length=150, default="TBA")

    class Meta:
        verbose_name = "Term"
        verbose_name_plural = "Terms"

    def __str__(self):
        return self.term

webapp/sptool/gui/models.py
from django.db import models

# Create your models here.

webapp/sptool/gui/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User as AuthUser
import requests

import os


class SignupForm(UserCreationForm):
    input_class = 'form-control'

    email = forms.EmailField(max_length=254, help_text='Required. Provide a valid email address',
                             label="Email")

    agree = forms.BooleanField()

    class Meta:
        input_class = 'form-control'

        model = AuthUser

        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

    def __init__(self, *args, **kwargs):

        site_url = os.environ.get("SITE_URL")
        api_key = os.environ.get("API_KEY")

        # dynamically get form fields
        response = requests.get(site_url + "/api/gender",
                                headers={
                                    "Api-Key": api_key,
                                },
                                )
        gender = list(zip(list(d["id"] for d in response.json()), list(d["gender"] for d in response.json())))
        self.base_fields["gender"] = forms.ChoiceField(choices=[("", "Select your gender")] + gender,
                                                       label="Gender")

        response = requests.get(site_url + "/api/age",
                                headers={
                                    "Api-Key": api_key,
                                },
                                )
        ages = list(zip(list(d["id"] for d in response.json()), list(d["age"] for d in response.json())))
        self.base_fields["age"] = forms.ChoiceField(choices=[("", "Select your age")] + ages,
                                                    label="Age")

        response = requests.get(site_url + "/api/country",
                                headers={
                                    "Api-Key": api_key,
                                },
                                )
        countries = list(zip(list(d["id"] for d in response.json()), list(d["country"] for d in response.json())))
        self.base_fields["country"] = forms.ChoiceField(choices=[("", "Select your country")] + countries,
                                                        label="Country")

        response = requests.get(site_url + "/api/education",
                                headers={
                                    "Api-Key": api_key,
                                },
                                )
        educations = list(zip(list(d["id"] for d in response.json()), list(d["education"] for d in response.json())))
        self.base_fields["education"] = forms.ChoiceField(choices=[("", "Select your education")] + educations,
                                                          label="Education")

        response = requests.get(site_url + "/api/occupation",
                                headers={
                                    "Api-Key": api_key,
                                },
                                )
        occupations = list(zip(list(d["id"] for d in response.json()), list(d["occupation"] for d in response.json())))
        self.base_fields["occupation"] = forms.ChoiceField(choices=[("", "Select your occupation")] + occupations,
                                                           label="Occupation")

        input_class = 'form-control'

        for field in self.base_fields.values():
            field.widget.attrs["placeholder"] = field.label
            field.widget.attrs["class"] = input_class
            field.widget.attrs["required"] = 'required'
        super(UserCreationForm, self).__init__(*args, **kwargs)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email and AuthUser.objects.filter(email=email).exists():
            raise forms.ValidationError(u'A user with that email already exists.')
        return email


class ProfileForm(forms.Form):

    first_name = forms.CharField(label="Name", max_length=100)
    last_name = forms.CharField(label="Surname", max_length=100)

    def __init__(self, *args, **kwargs):

        site_url = os.environ.get("SITE_URL")
        api_key = os.environ.get("API_KEY")

        # dynamically get form fields
        response = requests.get(site_url + "/api/gender",
                                headers={
                                    "Api-Key": api_key,
                                },
                                )
        gender = list(zip(list(d["id"] for d in response.json()), list(d["gender"] for d in response.json())))
        self.base_fields["gender"] = forms.ChoiceField(choices=gender,
                                                       label="Gender")

        response = requests.get(site_url + "/api/age",
                                headers={
                                    "Api-Key": api_key,
                                },
                                )
        ages = list(zip(list(d["id"] for d in response.json()), list(d["age"] for d in response.json())))
        self.base_fields["age"] = forms.ChoiceField(choices=ages,
                                                    label="Age")

        response = requests.get(site_url + "/api/country",
                                headers={
                                    "Api-Key": api_key,
                                },
                                )
        countries = list(zip(list(d["id"] for d in response.json()), list(d["country"] for d in response.json())))
        self.base_fields["country"] = forms.ChoiceField(choices=countries,
                                                        label="Country")

        response = requests.get(site_url + "/api/education",
                                headers={
                                    "Api-Key": api_key,
                                },
                                )
        educations = list(zip(list(d["id"] for d in response.json()), list(d["education"] for d in response.json())))
        self.base_fields["education"] = forms.ChoiceField(choices=educations,
                                                          label="Education")

        response = requests.get(site_url + "/api/occupation",
                                headers={
                                    "Api-Key": api_key,
                                },
                                )
        occupations = list(zip(list(d["id"] for d in response.json()), list(d["occupation"] for d in response.json())))
        self.base_fields["occupation"] = forms.ChoiceField(choices=occupations,
                                                           label="Occupation")

        input_class = 'form-control'

        for field in self.base_fields.values():
            field.widget.attrs["placeholder"] = field.label
            field.widget.attrs["class"] = input_class
            field.widget.attrs["required"] = 'required'
        super().__init__(*args, **kwargs)


class BusinessForm(forms.Form):

    def __init__(self, *args, **kwargs):

        site_url = os.environ.get("SITE_URL")
        api_key = os.environ.get("API_KEY")

        # dynamically get form fields
        response = requests.get(site_url + "/api/gender",
                                headers={
                                    "Api-Key": api_key,
                                },
                                )
        gender = list(zip(list(d["id"] for d in response.json()), list(d["gender"] for d in response.json())))
        self.base_fields["gender"] = forms.ChoiceField(choices=[("", "Select gender")] + gender,
                                                       label="Gender",
                                                       required=False)

        response = requests.get(site_url + "/api/age",
                                headers={
                                    "Api-Key": api_key,
                                },
                                )
        ages = list(zip(list(d["id"] for d in response.json()), list(d["age"] for d in response.json())))
        self.base_fields["age"] = forms.ChoiceField(choices=[("", "Select age")] + ages,
                                                    label="Age",
                                                    required=False)

        response = requests.get(site_url + "/api/country",
                                headers={
                                    "Api-Key": api_key,
                                },
                                )
        countries = list(zip(list(d["id"] for d in response.json()), list(d["country"] for d in response.json())))
        self.base_fields["country"] = forms.ChoiceField(choices=[("", "Select country")] + countries,
                                                        label="Country",
                                                        required=False)

        response = requests.get(site_url + "/api/education",
                                headers={
                                    "Api-Key": api_key,
                                },
                                )
        educations = list(zip(list(d["id"] for d in response.json()), list(d["education"] for d in response.json())))
        self.base_fields["education"] = forms.ChoiceField(choices=[("", "Select education")] + educations,
                                                          label="Education",
                                                          required=False)

        response = requests.get(site_url + "/api/occupation",
                                headers={
                                    "Api-Key": api_key,
                                },
                                )
        occupations = list(zip(list(d["id"] for d in response.json()), list(d["occupation"] for d in response.json())))
        self.base_fields["occupation"] = forms.ChoiceField(choices=[("", "Select occupation")] + occupations,

webapp/sptool/api/views/terms.py
from ..models import Term
from ..serializers import TermSerializer
from rest_framework import viewsets

from rest_framework_api_key.permissions import HasAPIAccess


class TermViewSet(viewsets.ModelViewSet):

    permission_classes = (HasAPIAccess,)

    queryset = Term.objects.all()
    serializer_class = TermSerializer

webapp/sptool/api/views/videos.py
from ..models import Video
from ..serializers import VideoSerializer
from rest_framework import viewsets
from rest_framework.response import Response
from rest_framework.decorators import api_view, permission_classes

from rest_framework_api_key.permissions import HasAPIAccess

from django.contrib.postgres.search import SearchQuery, SearchRank, SearchVector


class VideoViewSet(viewsets.ModelViewSet):

    permission_classes = (HasAPIAccess,)

    queryset = Video.objects.all()
    serializer_class = VideoSerializer

    lookup_field = "euscreen"


@api_view(['POST'])
@permission_classes((HasAPIAccess, ))
def search_videos(request, *args, **kwargs):

    if "query" in request.data:
        keywords = request.data["query"]
    else:
        return Response({"message": "no search query provided"})

    query = SearchQuery(keywords)

    topic_vector = SearchVector('topic', weight='A')
    title_vector = SearchVector('title', weight='B')
    summary_vector = SearchVector('summary', weight='C')
    vectors = topic_vector + title_vector + summary_vector

    qs = Video.objects.all()

    qs = qs.annotate(search=vectors).filter(search=query)
    qs = qs.annotate(rank=SearchRank(vectors, query)).order_by('-rank')

    result = []
    for video in qs:
        result.append({
            "euscreen": video.euscreen,
            "title": video.title,
            "topic": video.topic,
            "summary": video.summary
        })

    response = Response({"videos": result})

    return response

webapp/sptool/gui/templates/gui/about.html
{% extends 'gui/base.html' %}

{% block content %}

<div class="title">About</div>

<div align="justify">

    <p>Social Recommendation and Personalization Tool (SRPtool) consists of three main functionalities/mechanisms, as follows:</p>

    <ol>
        <li>Personalization</li>
        <li>Relevance Feedback</li>
        <li>Social Recommendation</li>
    </ol>

    <p>Those three main mechanisms are efficiently combined towards delivering personalized information to the end user (either professional or viewer) close to his/her interests, improving end users’ Quality of Experience (QoE) and making the overall PRODUCER toolkit’s usage more appealing. The output of the SRPtool will be the personalized information, which will be offered as appropriately ranked list of multimedia content either to professional users or to the viewers. For the latter, the most relevant content to user’s profile will be ranked higher in the list while for the former higher rank will be assigned to multimedia content that is most relevant to their customers’ characteristics. This personalized information will conclude to significant benefits and profit for the professional users, e.g. production houses, broadcasters, advertising companies, editorial and online publishing companies, etc., as well as it will encourage the usage of the tool by the viewers.</p>

    <p>The main goal of personalization mechanism is to effectively and efficiently satisfy individual needs. By considering end users as individuals, implicit characteristics such as personal taste, age, origin, innate needs and experience become important integral parts of system design. In the literature, personalized user interface has been popular by using implicit data captured in user interactions.</p>

    <p>The relevance feedback is utilized by the system to learn users’ specific context that they have in mind for the initial streamed video. More specifically, it should be noticed that starting with the same video, two users could end up with very different enrichments and relevant advertisements paired and shown with the video depending on their feedback which contributes to the update of user’s profile. Thus, the main goal of relevance feedback is to learn a model of user’s interest based on his/her interaction sessions with the system.</p>

    <p>The general scope of social recommendation mechanism is to collect and analyze different sources of information considering the preferences of the users with respect to a set of items, aiming to provide rankings and scores on these items tailored to each separate user, in order to facilitate the discovery and selection of items by the end user and improve his / her experience.</p>

</div>
{% endblock %}

webapp/sptool/gui/templates/gui/business.html
{% extends 'gui/base.html' %}

{% block content %}

    <div class="container" style="padding-bottom: 50px">
        <div class="title">Business</div>
        <hr>
        <div class="col-md-3">

            <div class="tile-title">Select Target Group</div>
            <hr>

        <form action="" method="post">
            {% csrf_token %}
            <div style="width: 90%;">

            <div class="control-group" style="padding-bottom: 5px;" >
                {{ form.gender }}
                <small style="color: red">{{ form.gender.errors }}</small>
            </div>

            <div class="control-group" style="padding-bottom: 5px;" >
                {{ form.age }}
                <small style="color: red">{{ form.age.errors }}</small>
            </div>

            <div class="control-group" style="padding-bottom: 5px;" >
                {{ form.country }}
                <small style="color: red">{{ form.country.errors }}</small>
            </div>

            <div class="control-group" style="padding-bottom: 5px;" >
                {{ form.occupation }}
                <small style="color: red">{{ form.occupation.errors }}</small>
            </div>

            <div class="control-group" style="padding-bottom: 5px;" >
                {{ form.education }}
                <small style="color: red">{{ form.education.errors }}</small>
            </div>

            <div style="text-align:center; padding-top: 20px">
                <input type="submit" class="btn btn-sm btn-primary btn-wide" value="Search">
            </div>

            </div>


        </form>

        </div><!-- /form -->

        <div class="col-md-5">
            <div class="tile-title">Videos</div>
            <hr>
            <div class="media attribution">
            <table class="table">
                <tbody>
                    {% if videos %}
                        {% for video in videos %}
                            <tr>
                                <td>
                                    <a class="inline" style="color: inherit;" data-toggle="collapse" data-parent="#accordion" href="#collapse{{ forloop.counter }}">{{ video.title }}</a>
                                    <div id="collapse{{ forloop.counter }}" class="panel-collapse collapse">
                                        <small>{{ video.summary }}</small>
                                    </div>
                                </td>
                                <td align="right"><a onclick="Recommend_enrichments({{ video }}, '{{ site_url }}', '{{ api_key }}')" href="#" class="fui-arrow-right"></a></td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <p>No information for the specified target group</p>
                        </tr>
                    {% endif %}
                </tbody>
            </table>

        </div>
        </div>


        <div class="col-md-4">
            <div class="tile-title">Enrichments</div>
            <hr>
            <form method="post" action="{% url 'export' %}">
                {% csrf_token %}

                <table class="table table-fixed">
                    <tbody id="enrichments">
                    <!-- HERE GO THE ENRICHMENTS GENERATED FROM THE API REQUEST -->
                    </tbody>
                </table>
                <div style="text-align:center; padding-top: 20px">
                    <input type="submit" class="btn btn-sm btn-primary btn-wide" value="Export">
                </div>

            </form>
        </div>
    </div> <!-- /container -->

    <script>
    function Recommend_enrichments(video, site_url, api_key) {
        var csrftoken = Cookies.get('csrftoken');
        var xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange=function()
        {
            if (xhttp.readyState==4 && xhttp.status==200)
            {
                var response = JSON.parse(xhttp.responseText);
                Display_enrichments(response, site_url, api_key);
            }
        };
        // open(method, url, asynchronous)
        xhttp.open("POST", site_url.toString() + "/api/enrichments_to_target", false);
        xhttp.setRequestHeader("Content-type", "application/json");
        xhttp.setRequestHeader("X-CSRFToken", csrftoken);
        xhttp.setRequestHeader("Api-Key", api_key);
        var data = JSON.stringify({
            "euscreen": video["euscreen"].toString(),
            "num": 0});

        xhttp.send(data);
        var response = JSON.parse(xhttp.responseText);
        console.log(response);
    }

    function Display_enrichments(response, site_url, api_key) {
        var out = "";
        var i;
        var enrichments_list = response["representative 1"]["enrichments"];

        if (enrichments_list.length == 0) {
            out += '<tr>' +
                    '<td>' +
                        '<p>No enrichments yet on this video</p>' +
                    '</td>' +
                '</tr>';
        }

        else {
            enrichments_list.sort(function(a, b) {
                return parseFloat(a.start_time) - parseFloat(b.start_time);
            });

            for(i = 0; i < enrichments_list.length; i++) {
                var request = new XMLHttpRequest();
                request.open("GET", site_url.toString() + "/api/enrichment/" + enrichments_list[i].id.toString() + "/", false);

                request.setRequestHeader("Api-Key", api_key);
                request.send();
                var enrichment = JSON.parse(request.responseText);
                out += '<tr>' +
                        '<td>' +
                            '<img src="' + enrichment.thumbnail + '" class="img-circle" alt="missing image" width="50px" height="50px" style="margin: 10px;">' +
                            '<a class="inline" data-toggle="collapse" data-parent="#accordion" href="#collapse_enrichment' + i + '">' + enrichment.enrichment_id + '</a>' +
                            '<div class="inline" style="padding-left: 2px">[' + enrichments_list[i].start_time + ']</div>' +

                            '<div class="material-switch pull-right">' +
                                '<input checked name="checked" id="option' + i + '" name="someSwitchOption001" type="checkbox" value="' + enrichment.enrichment_id + '@' + enrichments_list[i].start_time + '"/>' + // @ is used to pass both enrichment ID and the TIME
                                '<label for="option' + i + '" class="label-danger"></label>' +
                            '</div>' +
                            '<div id="collapse_enrichment' + i + '" class="panel-collapse collapse">' + enrichment.overlay_text_description + '</div>' +

                        '</td>' +
                    '</tr>';
            }
        }

        document.getElementById("enrichments").innerHTML= out;
    }
    </script>

{% endblock %}

webapp/sptool/gui/templates/gui/dashboard.html
<div class="logged-in-box auth0-box logged-in">
    <h1 id="logo"><img src="//cdn.auth0.com/samples/auth0_logo_final_blue_RGB.png" /></h1>
    <img class="avatar" src="{{ auth0User.extra_data.picture }}"/>
    <h2>Welcome {{ user.username }}</h2>
    <pre>{{ userdata }}</pre>
</div>

webapp/sptool/gui/templates/gui/home.html
{% extends 'gui/base.html' %}

{% block content %}

    {% load static %}
    <div class="title">Welcome to the Personalized Experience Mechanism </div>
    <div align="center"> <img class="img-responsive" src="{% static '/gui/images/sp_tool.png' %}" /></div></h1>

{% endblock %}

webapp/sptool/gui/templates/gui/signup.html
{% extends 'gui/base.html' %}

{% block content %}


    {% if user.is_authenticated %}
        <div class="container" style="width:500px">
            <div class="alert alert-primary" role="alert">
                <h4 class="alert-heading">You are already logged in!</h4>
            </div>
        </div>

    {% else %}

    <div class="container" style="width:500px; padding-bottom: 50px">
        <div class="title">Sign Up</div>
        <hr>
        <div class="login-form">

        <form action="" method="post">
            {% csrf_token %}

            <div class="control-group" style="width:400px" >
                <div class="input-icon fui-user" for="login-name"></div>
                {{ form.username }}
                <small style="color: red">{{ form.username.errors }}</small>
            </div>

            <div class="control-group inline" style="width:199px">
                {{ form.first_name }}
                <small style="color: red">{{ form.first_name.errors }}</small>
            </div>

            <div class="control-group inline" style="width:199px">
                {{ form.last_name }}
                <small style="color: red">{{ form.last_name.errors }}</small>
            </div>

            <div class="control-group" style="width:400px" >
                <div class="input-icon fui-mail" for="login-email"></div>
                {{ form.email }}
                <small style="color: red">{{ form.email.errors }}</small>
            </div>

            <div class="control-group" style="width:400px" >
                <div class="input-icon fui-heart"></div>
                {{ form.gender }}
                <small style="color: red">{{ form.gender.errors }}</small>
            </div>

            <div class="control-group" style="width:400px" >
                <div class="input-icon fui-time"></div>
                {{ form.age }}
                <small style="color: red">{{ form.age.errors }}</small>
            </div>

            <div class="control-group" style="width:400px" >
                <div class="input-icon fui-home"></div>
                {{ form.country }}
                <small style="color: red">{{ form.country.errors }}</small>
            </div>

            <div class="control-group" style="width:400px" >
                <div class="input-icon fui-document"></div>
                {{ form.occupation }}
                <small style="color: red">{{ form.occupation.errors }}</small>
            </div>

            <div class="control-group" style="width:400px" >
                <div class="input-icon fui-bookmark"></div>
                {{ form.education }}
                <small style="color: red">{{ form.education.errors }}</small>
            </div>

            <div class="control-group" style="width:400px">
                <div class="input-icon fui-lock" for="login-pass"></div>
                {{ form.password1 }}
                <small style="color: red">{{ form.password1.errors }}</small>
            </div>

            <div class="control-group" style="width:400px">
                <div class="input-icon fui-lock" for="login-pass"></div>
                {{ form.password2 }}
                <small style="color: red">{{ form.password2.errors }}</small>
            </div>

            <div style="width:400px">
                <div class="input-icon fui-question-circle"></div>
                <div class="item">
                    {{ form.agree }}
                    <label for="id_agree" style="display:inline; position:relative; padding-left: 12px; bottom: 5px">Do you agree with the <a href="{% url "terms" %}" target="_blank">Terms and Conditions</a> of the service?</label>
                </div>
                <small style="color: red">{{ form.agree.errors }}</small>
            </div>

            <div style="text-align:center; padding-top: 20px">
                <input type="submit" class="btn btn-hg btn-primary btn-wide" value="Sign Up">
            </div>
        </form>

        </div><!-- /login-form -->
    </div> <!-- /container -->

    {% endif %}

{% endblock %}